Update Run_main.go_and_Push_Generated_File.yml
Signed-off-by: REIJI007 <miyajimareji007@gmail.com>

diff --git a/.github/workflows/Run_main.go_and_Push_Generated_File.yml b/.github/workflows/Run_main.go_and_Push_Generated_File.yml
--- a/.github/workflows/Run_main.go_and_Push_Generated_File.yml
+++ b/.github/workflows/Run_main.go_and_Push_Generated_File.yml
@@ -31,6 +31,10 @@ jobs:
         run: |
           cd mymodule
           go run main.go
+          if [ ! -f adblock_geosite.dat ]; then
+            echo "Error: adblock_geosite.dat was not generated."
+            exit 1
+          fi
 
       - name: Configure Git
         run: |
